# Be sure to restart your server when you modify this file.

default: &default
  features:
    auditing_allocation: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  features:
    auditing_allocation: <%= ENV['FEATURE_AUDITING_ALLOCATION'].present? %>
